version: 2

sources:
  - name: ethereum_nft_metadata
    tables:
      - name: nft_tokens
        external:
          location: s3a://ifcrypto/external/nft_metadata/nft_tokens
          using: csv
          options:
            header: "true"

      - name: nft_token_metadata
        external:
          location: s3a://ifcrypto/external/nft_metadata/nft_token_metadata_fixed
          using: parquet
          options:
            header: "true"
